# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_s2have <- function(input) {
    .Call(`_dken_cpp_s2have`, input)
}

cpp_test2 <- function() {
    .Call(`_dken_cpp_test2`)
}

